export const TAG_GET_FILTER_DATA = 'GET_FILTER_DATA';
export const TAG_GET_FILTER_DATA_BY_QUERY_TEXT =
  'GET_FILTER_DATA_BY_QUERY_TEXT';
export const TAG_GET_FILTER_DETAILS = 'TAG_GET_FILTER_DETAILS';
export const TAG_GET_PROJECTS = 'TAG_GET_PROJECTS';
export const TAG_GET_PROJECT_DETAILS_BY_ID = 'TAG_GET_PROJECT_DETAILS_BY_ID';
export const TAG_GET_USERS_IN_COMAPNY = 'TAG_GET_USERS_IN_COMAPNY';
export const TAG_GET_CHAT_HISTORY = 'TAG_GET_CHAT_HISTORY';
export const TAG_GET_SESSION_DETAILS = 'TAG_GET_SESSION_DETAILS';
export const TAG_GET_ALL_ASSESSMENT = 'TAG_GET_ALL_ASSESSMENT';
export const TAG_GET_ASSESSEMENT = 'TAG_GET_ASSESSEMENT';
export const TAG_GET_QUESTIONS_FOR_ASSESSMENT =
  'TAG_GET_QUESTIONS_FOR_ASSESSMENT';
export const TAG_GET_ALL_ASSESSMENT_LINKS = 'TAG_GET_ALL_ASSESSMENT_LINKS';
export const TAG_GET_REPORTS_FOR_ASSESSMENT = 'TAG_GET_REPORTS_FOR_ASSESSMENT';
export const TAG_GET_ALL_MEETINGS = 'TAG_GET_ALL_MEETINGS';
export const TAG_GET_MEETING_BY_ID = 'TAG_GET_MEETING_BY_ID';
export const TAG_GET_USER_STATUS = 'TAG_GET_USER_STATUS';

export const ALL_TAGS_TYPE = [
  TAG_GET_FILTER_DATA,
  TAG_GET_FILTER_DATA_BY_QUERY_TEXT,
  TAG_GET_FILTER_DETAILS,
  TAG_GET_PROJECTS,
  TAG_GET_PROJECT_DETAILS_BY_ID,
  TAG_GET_USERS_IN_COMAPNY,
  TAG_GET_CHAT_HISTORY,
  TAG_GET_SESSION_DETAILS,
  TAG_GET_ALL_ASSESSMENT,
  TAG_GET_ASSESSEMENT,
  TAG_GET_QUESTIONS_FOR_ASSESSMENT,
  TAG_GET_ALL_ASSESSMENT_LINKS,
  TAG_GET_REPORTS_FOR_ASSESSMENT,
  TAG_GET_ALL_MEETINGS,
  TAG_GET_MEETING_BY_ID,
  TAG_GET_USER_STATUS,
];
